<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Page Remove="SpinnerControl.xaml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="SpinnerControl.xaml" />
  </ItemGroup>

</Project>
